import { SlashCommandBuilder, PermissionFlagsBits } from "discord.js";
import { pool } from "../database/pool.js";
export const data=new SlashCommandBuilder().setName("events").setDescription("Event attendance, host requests, and LOA.")
.addSubcommand(s=>s.setName("host-request").setDescription("Request permission to host.").addStringOption(o=>o.setName("event").setDescription("Requested event").setRequired(true)))
.addSubcommand(s=>s.setName("create").setDescription("Create event session.").addStringOption(o=>o.setName("title").setDescription("Title").setRequired(true)).addStringOption(o=>o.setName("type").setDescription("Type").setRequired(true)))
.addSubcommand(s=>s.setName("checkin").setDescription("Check into latest open event."))
.addSubcommand(s=>s.setName("checkout").setDescription("Check out of latest event."))
.addSubcommand(s=>s.setName("close").setDescription("Close your latest event."))
.addSubcommand(s=>s.setName("loa-request").setDescription("Request leave of absence.").addStringOption(o=>o.setName("reason").setDescription("Reason").setRequired(true)).addIntegerOption(o=>o.setName("days").setDescription("Days").setRequired(true).setMinValue(1).setMaxValue(90)))
.addSubcommand(s=>s.setName("loa-status").setDescription("View LOA status."))
.addSubcommand(s=>s.setName("loa-cancel").setDescription("Cancel pending LOA."));
export async function execute(i){const s=i.options.getSubcommand();if(s==="host-request")return i.reply({content:`Host request submitted for **${i.options.getString("event",true)}**.`,ephemeral:true});if(s==="create"){if(!i.memberPermissions.has(PermissionFlagsBits.ManageEvents))return i.reply({content:"Manage Events required.",ephemeral:true});const r=await pool.query(`INSERT INTO event_sessions(guild_id,event_type,host_id,title) VALUES($1,$2,$3,$4) RETURNING id`,[i.guildId,i.options.getString("type",true),i.user.id,i.options.getString("title",true)]);return i.reply(`Event **#${r.rows[0].id}** created.`);}if(s==="checkin"||s==="checkout"){const e=await pool.query(`SELECT * FROM event_sessions WHERE guild_id=$1 AND status='open' ORDER BY id DESC LIMIT 1`,[i.guildId]);if(!e.rows[0])return i.reply({content:"No open event.",ephemeral:true});if(s==="checkin"){await pool.query(`INSERT INTO event_checkins(event_id,discord_user_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[e.rows[0].id,i.user.id]);return i.reply({content:`Checked into event #${e.rows[0].id}.`,ephemeral:true});}await pool.query(`UPDATE event_checkins SET checked_out_at=NOW() WHERE event_id=$1 AND discord_user_id=$2`,[e.rows[0].id,i.user.id]);return i.reply({content:`Checked out of event #${e.rows[0].id}.`,ephemeral:true});}if(s==="close"){await pool.query(`UPDATE event_sessions SET status='closed',closed_at=NOW() WHERE host_id=$1 AND status='open'`,[i.user.id]);return i.reply({content:"Your open event was closed.",ephemeral:true});}if(s==="loa-request"){const d=i.options.getInteger("days",true),r=i.options.getString("reason",true);await pool.query(`INSERT INTO loa_requests(discord_user_id,reason,ends_at) VALUES($1,$2,NOW()+($3||' days')::interval)`,[i.user.id,r,d]);return i.reply({content:`LOA requested for ${d} days.`,ephemeral:true});}if(s==="loa-cancel"){await pool.query(`UPDATE loa_requests SET status='cancelled' WHERE discord_user_id=$1 AND status='pending'`,[i.user.id]);return i.reply({content:"Pending LOA cancelled.",ephemeral:true});}const r=await pool.query(`SELECT * FROM loa_requests WHERE discord_user_id=$1 ORDER BY id DESC LIMIT 1`,[i.user.id]);return i.reply({content:r.rows[0]?`Status: **${r.rows[0].status}**\nReason: ${r.rows[0].reason}`:"No LOA record.",ephemeral:true});}
