import { SlashCommandBuilder, PermissionFlagsBits } from "discord.js";
import { pool } from "../database/pool.js";
export const data=new SlashCommandBuilder().setName("legal").setDescription("Counseling, NJP, and investigations.")
.addSubcommand(s=>s.setName("counsel").setDescription("Record counseling.").addUserOption(o=>o.setName("member").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("reason").setDescription("Reason").setRequired(true)))
.addSubcommand(s=>s.setName("njp-create").setDescription("Open NJP case.").addUserOption(o=>o.setName("member").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("details").setDescription("Details").setRequired(true)))
.addSubcommand(s=>s.setName("njp-view").setDescription("View NJP case.").addIntegerOption(o=>o.setName("case").setDescription("Case ID").setRequired(true)))
.addSubcommand(s=>s.setName("njp-close").setDescription("Close NJP case.").addIntegerOption(o=>o.setName("case").setDescription("Case ID").setRequired(true)))
.addSubcommand(s=>s.setName("investigation-open").setDescription("Open investigation.").addUserOption(o=>o.setName("member").setDescription("Member").setRequired(true)).addStringOption(o=>o.setName("details").setDescription("Details").setRequired(true)))
.addSubcommand(s=>s.setName("investigation-update").setDescription("Update investigation.").addIntegerOption(o=>o.setName("case").setDescription("Case ID").setRequired(true)).addStringOption(o=>o.setName("details").setDescription("Update").setRequired(true)))
.addSubcommand(s=>s.setName("investigation-close").setDescription("Close investigation.").addIntegerOption(o=>o.setName("case").setDescription("Case ID").setRequired(true)))
.setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild);
export async function execute(i){const s=i.options.getSubcommand();if(s==="counsel"){const u=i.options.getUser("member",true),r=i.options.getString("reason",true);await pool.query(`INSERT INTO member_notes(target_discord_id,author_discord_id,note) VALUES($1,$2,$3)`,[u.id,i.user.id,`COUNSELING: ${r}`]);return i.reply(`${u} counseling recorded.`);}if(s==="njp-create"){const u=i.options.getUser("member",true),d=i.options.getString("details",true),r=await pool.query(`INSERT INTO njp_cases(target_discord_id,opened_by,details) VALUES($1,$2,$3) RETURNING id`,[u.id,i.user.id,d]);return i.reply(`NJP case **#${r.rows[0].id}** opened for ${u}.`);}if(s==="njp-view"){const id=i.options.getInteger("case",true),r=await pool.query(`SELECT * FROM njp_cases WHERE id=$1`,[id]);return i.reply({content:r.rows[0]?`**NJP #${id}**\nTarget: <@${r.rows[0].target_discord_id}>\nStatus: ${r.rows[0].status}\n${r.rows[0].details}`:"Case not found.",ephemeral:true});}if(s==="njp-close"){const id=i.options.getInteger("case",true);await pool.query(`UPDATE njp_cases SET status='closed',closed_at=NOW() WHERE id=$1`,[id]);return i.reply(`NJP case **#${id}** closed.`);}if(s==="investigation-open"){const u=i.options.getUser("member",true),d=i.options.getString("details",true),r=await pool.query(`INSERT INTO investigations(target_discord_id,opened_by,details) VALUES($1,$2,$3) RETURNING id`,[u.id,i.user.id,d]);return i.reply(`Investigation **#${r.rows[0].id}** opened for ${u}.`);}const id=i.options.getInteger("case",true);if(s==="investigation-update"){await pool.query(`UPDATE investigations SET details=details||E'\n'||$2,updated_at=NOW() WHERE id=$1`,[id,i.options.getString("details",true)]);return i.reply(`Investigation **#${id}** updated.`);}await pool.query(`UPDATE investigations SET status='closed',closed_at=NOW(),updated_at=NOW() WHERE id=$1`,[id]);return i.reply(`Investigation **#${id}** closed.`);}
