import { SlashCommandBuilder, PermissionFlagsBits } from "discord.js";
import { listEntities,upsertEntity,deleteEntity } from "../services/configService.js";
export const data=new SlashCommandBuilder().setName("org").setDescription("Create and manage divisions, units, and billets.")
.addSubcommand(s=>s.setName("create").setDescription("Create organization entity.").addStringOption(o=>o.setName("type").setDescription("Type").setRequired(true).addChoices({name:"Division",value:"division"},{name:"Unit",value:"unit"},{name:"Billet",value:"billet"})).addStringOption(o=>o.setName("key").setDescription("Unique key").setRequired(true)).addStringOption(o=>o.setName("name").setDescription("Name").setRequired(true)).addStringOption(o=>o.setName("parent").setDescription("Parent key")).addRoleOption(o=>o.setName("role").setDescription("Discord role")).addStringOption(o=>o.setName("team").setDescription("Roblox team")))
.addSubcommand(s=>s.setName("edit").setDescription("Edit organization entity.").addStringOption(o=>o.setName("type").setDescription("Type").setRequired(true).addChoices({name:"Division",value:"division"},{name:"Unit",value:"unit"},{name:"Billet",value:"billet"})).addStringOption(o=>o.setName("key").setDescription("Key").setRequired(true)).addStringOption(o=>o.setName("name").setDescription("Name").setRequired(true)).addStringOption(o=>o.setName("parent").setDescription("Parent key")).addRoleOption(o=>o.setName("role").setDescription("Discord role")).addStringOption(o=>o.setName("team").setDescription("Roblox team")))
.addSubcommand(s=>s.setName("delete").setDescription("Delete entity.").addStringOption(o=>o.setName("type").setDescription("Type").setRequired(true).addChoices({name:"Division",value:"division"},{name:"Unit",value:"unit"},{name:"Billet",value:"billet"})).addStringOption(o=>o.setName("key").setDescription("Key").setRequired(true)))
.addSubcommand(s=>s.setName("list").setDescription("List entities.").addStringOption(o=>o.setName("type").setDescription("Optional type").addChoices({name:"Division",value:"division"},{name:"Unit",value:"unit"},{name:"Billet",value:"billet"})))
.setDefaultMemberPermissions(PermissionFlagsBits.Administrator);
export async function execute(i){const s=i.options.getSubcommand(),type=i.options.getString("type");if(s==="list"){const r=await listEntities(i.guildId,type);return i.reply({content:r.length?["**Organization**",...r.map(x=>`\`${x.entity_type}:${x.entity_key}\` — **${x.name}**${x.parent_key?` (parent: ${x.parent_key})`:""}`)].join("\n"):"No entities found.",ephemeral:true});}const key=i.options.getString("key",true).toLowerCase();if(s==="delete"){const r=await deleteEntity(i.guildId,type,key);return i.reply({content:r?`Deleted **${r.name}**.`:"Not found.",ephemeral:true});}const r=await upsertEntity({guildId:i.guildId,type,key,name:i.options.getString("name",true),parentKey:i.options.getString("parent"),roleId:i.options.getRole("role")?.id,teamName:i.options.getString("team"),actorId:i.user.id});return i.reply({content:`Saved **${r.name}** (${r.entity_type}).`,ephemeral:true});}
